facade.cache:
  module: monosloth.facade
  class: CacheFacade

facade.config:
  module: monosloth.facade
  class: ConfigFacade

facade.resolve:
  module: monosloth.facade
  class: ResolveFacade

facade.logger:
  module: monosloth.facade
  class: LoggerFacade

facade.app:
  module: monosloth.facade
  class: AppFacade
