provider.config:
  module: monosloth.provider
  class: ConfigProvider

provider.decorator:
  module: monosloth.provider
  class: DecoratorProvider
  dependencies:
    - decorator.inject

provider.facade:
  module: monosloth.provider
  class: FacadeProvider
  dependencies:
    - facade.cache
    - facade.config
    - facade.resolve
    - facade.app
    - facade.environment
    - facade.dispatch

provider.cache:
  module: monosloth.provider
  class: CacheProvider

provider.environment:
  module: monosloth.provider
  class: EnvironmentProvider

provider.database:
  module: monosloth.provider
  class: DatabaseProvider

provider.command:
  module: monosloth.provider
  class: CommandProvider
  dependencies:
    - commands.inspire
